name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get submodules
      run: git submodule update --init --recursive

    - name: Update apt
      run: sudo apt-get update --fix-missing
    
    - name: Install tree & valgrind
      run: sudo apt-get install tree valgrind

    - name: Run tree
      run: tree

    - name: Make program
      run: make

    - name: Re-make program
      run: make re

    - name: View Contents of Libft
      run: nm -C libft/build/libft.a

    - name: View Contents of minishell
      run: nm -C minishell
    
    - name: Run Non-Interactive mode
      run: ./minishell -c 'ifconfig > file.txt; ifconfig | hexdump >> file.txt; echo $PATH >> file.txt; cat < file.txt'

    - name: Run Non-Interactibe mode with valgrind
      run: valgrind --leak-check=full --track-origins=yes --show-reachable=no ./minishell -c 'ifconfig > file.txt; ifconfig | hexdump >> file.txt; echo $PATH >> file.txt; cat < file.txt'